version: '3.3'
services:
  site:
    image: quizbot
    env_file:
      - ".keys"
    environment:
      DEBUG: "true"
      USE_SOCKS5_PROXY: "true"
      USE_TELEGRAM_WEBHOOK: "false"
      PERSISTENCE_DATA_FILE: "/usr/src/app/data/persistence.pkl"
      MONGO_HOST: "mongo:27017"
    restart: always
    volumes:
      - "./data/bot_data:/usr/src/app/data"
    links:
      - mongo

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - "./data/mongodb_data:/data/db"
